D = float(input("input distance (km.) : "))
T = float(input("input time (hr.) : "))
print("-------------------------------")
print("Your speed is : ", D/T, "km/hr")
print("-------------------------------")
